SET FOREIGN_KEY_CHECKS = 0;

-- -------------------------------------------------------------
-- DROP in reverse dependency order (children before parents)
-- -------------------------------------------------------------
DROP TABLE IF EXISTS transaction_participants;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS system_logs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS transaction_categories;

SET FOREIGN_KEY_CHECKS = 1;


-- -------------------------------------------------------------
-- CREATE parent tables (no foreign key dependencies)
-- -------------------------------------------------------------

-- Axcel's table
CREATE TABLE transaction_categories (
    category_id   INT          NOT NULL AUTO_INCREMENT COMMENT 'Surrogate primary key, auto-generated integer identifying the category',
    category_code VARCHAR(30)  NOT NULL                COMMENT 'Short machine-readable code matching transaction_type ENUM e.g. INCOMING, TRANSFER_SENT',
    description   VARCHAR(120) NULL                    COMMENT 'Human-readable explanation of what this transaction category means',

    PRIMARY KEY (category_id),
    UNIQUE KEY uq_category_code (category_code)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='Lookup table for MoMo SMS transaction types';


-- Beni's table
CREATE TABLE users (
    user_id    INT          NOT NULL AUTO_INCREMENT     COMMENT 'Surrogate primary key, autogenerated integer, uniquely identifies each user',
    full_name  VARCHAR(120) NOT NULL                    COMMENT 'Full name of the person or organisation as printed in the SMS message',
    phone      VARCHAR(20)  NULL                        COMMENT 'Phone number stored as text because values can be masked e.g. *********013 or carry a country prefix e.g. 250791666666',
    user_type  ENUM(
                   'CUSTOMER',
                   'AGENT',
                   'MERCHANT',
                   'OWNER'
               )            NOT NULL DEFAULT 'CUSTOMER' COMMENT 'Classifies the user role: CUSTOMER for ordinary users, AGENT for MoMo agents, MERCHANT for businesses, OWNER for the account holder',
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp when this user record was first inserted by the pipeline',

    PRIMARY KEY (user_id)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='Stores every distinct person or organisation involved in a MoMo transaction';


-- Dianah's table
CREATE TABLE system_logs (
    log_id     BIGINT       NOT NULL AUTO_INCREMENT                COMMENT 'Auto-generated unique identifier for each log entry, BIGINT because a long-running pipeline generates very many rows',
    log_level  ENUM('INFO','WARNING','ERROR') NOT NULL             COMMENT 'Severity of the pipeline event: INFO for success, WARNING for partial issues, ERROR for failures',
    message    VARCHAR(255) NULL                                   COMMENT 'Human-readable description of what happened during processing',
    logged_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP     COMMENT 'Timestamp when this log entry was recorded by the pipeline',

    PRIMARY KEY (log_id)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='Audit trail for the MoMo SMS data pipeline';


-- -------------------------------------------------------------
-- CREATE child tables (depend on parents above)
-- -------------------------------------------------------------

-- Lancelot's transactions table
CREATE TABLE transactions (
    transaction_id       BIGINT        NOT NULL AUTO_INCREMENT COMMENT 'Surrogate primary key, internal row identifier, not the provider ID',
    momo_tx_id           BIGINT        NULL                   COMMENT 'Provider TxId or Financial Transaction Id parsed from SMS body; NULL when SMS has no ID',
    sms_unix_timestamp   BIGINT        NOT NULL               COMMENT 'Raw Unix timestamp in ms from the XML date attribute',
    transaction_date     DATETIME      NOT NULL               COMMENT 'Datetime of the transaction parsed from the SMS body text',
    transaction_type     ENUM(
                             'INCOMING',
                             'MERCHANT_PAYMENT',
                             'BANK_DEPOSIT',
                             'TRANSFER_SENT',
                             'AIRTIME',
                             'BUNDLE',
                             'MERCHANT_DEBIT',
                             'AGENT_WITHDRAWAL'
                         )             NOT NULL               COMMENT 'Transaction pattern type derived from SMS body structure',
    direction            ENUM(
                             'CREDIT',
                             'DEBIT'
                         )             NOT NULL               COMMENT 'CREDIT when money enters the account, DEBIT when money leaves',
    amount               DECIMAL(12,2) NOT NULL               COMMENT 'Principal amount of the transaction in RWF',
    fee                  DECIMAL(12,2) NOT NULL DEFAULT 0.00  COMMENT 'Fee charged in RWF; defaults to 0 when not stated in SMS',
    new_balance          DECIMAL(12,2) NULL                   COMMENT 'Account balance reported after the transaction in RWF; nullable because some messages omit it',
    counterparty_name    VARCHAR(120)  NULL                   COMMENT 'Name of the other party as printed in the SMS body',
    counterparty_phone   VARCHAR(20)   NULL                   COMMENT 'Phone number of the other party; stored as text, may be masked e.g. *********013',
    counterparty_account VARCHAR(30)   NULL                   COMMENT 'Other party or agent account number when printed in the SMS',
    momo_account         VARCHAR(30)   NULL                   COMMENT 'Account owners own MoMo account number when printed in the message',
    receiver_code        VARCHAR(20)   NULL                   COMMENT 'Merchant short code appended after receiver name in payment SMS e.g. 12845',
    token                VARCHAR(100)  NULL                   COMMENT 'Token string returned for airtime or Cash Power purchases',
    external_tx_id       VARCHAR(40)   NULL                   COMMENT 'External Transaction Id present only on merchant debit messages',
    category_id          INT           NOT NULL               COMMENT 'FK to transaction_categories.category_id',
    log_id               BIGINT        NULL                   COMMENT 'FK to system_logs.log_id, the ingestion record that produced this row',
    raw_body             TEXT          NOT NULL               COMMENT 'Original SMS body text kept for audit and re-parsing',
    created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp when this row was inserted by the pipeline',

    PRIMARY KEY (transaction_id),
    UNIQUE KEY uq_momo_tx_id (momo_tx_id),

    CONSTRAINT chk_amount_positive      CHECK (amount      > 0),
    CONSTRAINT chk_fee_non_negative     CHECK (fee         >= 0),
    CONSTRAINT chk_balance_non_negative CHECK (new_balance IS NULL OR new_balance >= 0),

    CONSTRAINT fk_tx_category FOREIGN KEY (category_id)
        REFERENCES transaction_categories(category_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_tx_log FOREIGN KEY (log_id)
        REFERENCES system_logs(log_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    INDEX idx_transaction_date (transaction_date),
    INDEX idx_transaction_type (transaction_type),
    INDEX idx_category_id      (category_id),
    INDEX idx_direction        (direction)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='One row per MoMo SMS transaction parsed by the pipeline';


-- Lancelot's junction table
CREATE TABLE transaction_participants (
    participant_id BIGINT   NOT NULL AUTO_INCREMENT COMMENT 'Surrogate primary key for this participation record',
    transaction_id BIGINT   NOT NULL                COMMENT 'FK to transactions.transaction_id',
    user_id        INT      NOT NULL                COMMENT 'FK to users.user_id',
    role           ENUM(
                       'SENDER',
                       'RECEIVER',
                       'AGENT',
                       'MERCHANT',
                       'ACCOUNT_OWNER',
                       'DEPOSITOR'
                   )        NOT NULL                COMMENT 'Role this user played in the transaction',
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row insertion timestamp',

    PRIMARY KEY (participant_id),
    UNIQUE KEY uq_tx_user_role (transaction_id, user_id, role),

    CONSTRAINT fk_tp_transaction FOREIGN KEY (transaction_id)
        REFERENCES transactions(transaction_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_tp_user FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    INDEX idx_tp_transaction_id (transaction_id),
    INDEX idx_tp_user_id        (user_id)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='Junction table: one row per (transaction, user, role) combination';


-- -------------------------------------------------------------
-- Additional indexes
-- (only columns not already indexed inside CREATE TABLE blocks)
-- -------------------------------------------------------------
CREATE INDEX idx_users_phone    ON users(phone);
CREATE INDEX idx_logs_level     ON system_logs(log_level);
CREATE INDEX idx_logs_logged_at ON system_logs(logged_at);


-- -------------------------------------------------------------
-- INSERT seed data — parents before children
-- -------------------------------------------------------------

-- Categories — inserted in order so auto-increment IDs
-- match the category_id values in Lancelot's transaction rows
INSERT INTO transaction_categories (category_code, description) VALUES
    ('INCOMING',         'Money received from another MoMo user'),
    ('MERCHANT_PAYMENT', 'Payment made to a merchant or individual'),
    ('TRANSFER_SENT',    'Money transferred to another MoMo account'),
    ('BANK_DEPOSIT',     'Deposit added from a bank account into MoMo'),
    ('AIRTIME',          'Airtime purchase from MoMo balance'),
    ('MERCHANT_DEBIT',   'Merchant debit with external transaction ID'),
    ('BUNDLE',           'Bundle or data pack purchase from MoMo balance'),
    ('AGENT_WITHDRAWAL', 'Cash withdrawal through a MoMo agent');


-- Users — Beni's sample data
INSERT INTO users (full_name, phone, user_type) VALUES
    ('Jane Smith',    '250781234013', 'CUSTOMER'),
    ('Samuel Carter', '250791666666', 'CUSTOMER'),
    ('Linda Green',   '250788123456', 'MERCHANT'),
    ('Alex Doe',      '250722345678', 'AGENT'),
    ('Robert Brown',  '250733456789', 'CUSTOMER');


-- System logs — Dianah's sample data
INSERT INTO system_logs (log_level, message) VALUES
    ('INFO',    'Successfully parsed SMS at index 1 - received transaction'),
    ('INFO',    'Successfully parsed SMS at index 2 - payment transaction'),
    ('WARNING', 'SMS at index 45 matched no known pattern - skipped'),
    ('ERROR',   'SMS at index 67 - malformed date field, could not parse'),
    ('INFO',    'Pipeline completed - 1688 records processed, 3 skipped');


-- Transactions — Lancelot's sample data from actual XML
INSERT INTO transactions (
    momo_tx_id, sms_unix_timestamp, transaction_date,
    transaction_type, direction, amount, fee, new_balance,
    counterparty_name, counterparty_phone, counterparty_account,
    momo_account, receiver_code, token, external_tx_id,
    category_id, log_id, raw_body
) VALUES
(76662021700,  1715351458724, '2024-05-10 16:30:51', 'INCOMING',         'CREDIT', 2000.00,   0.00,  2000.00, 'Jane Smith',        '*********013', NULL, NULL, NULL,    NULL, NULL,                                   1, 1, 'You have received 2000 RWF from Jane Smith (*********013) on your mobile money account at 2024-05-10 16:30:51. Your new balance:2000 RWF. Financial Transaction Id: 76662021700.'),
(73214484437,  1715351506754, '2024-05-10 16:31:39', 'MERCHANT_PAYMENT', 'DEBIT',  1000.00,   0.00,  1000.00, 'Jane Smith',        NULL,           NULL, NULL, '12845', NULL, NULL,                                   2, 2, 'TxId: 73214484437. Your payment of 1,000 RWF to Jane Smith 12845 has been completed at 2024-05-10 16:31:39. Your new balance: 1,000 RWF. Fee was 0 RWF.'),
(NULL,         1715445936412, '2024-05-11 18:43:49', 'BANK_DEPOSIT',     'CREDIT', 40000.00,  0.00, 40400.00, NULL,                '250795963036', NULL, NULL, NULL,    NULL, NULL,                                   4, 3, '*113*R*A bank deposit of 40000 RWF has been added to your mobile money account at 2024-05-11 18:43:49. Your NEW BALANCE :40400 RWF.'),
(NULL,         1715452495316, '2024-05-11 20:34:47', 'TRANSFER_SENT',    'DEBIT',  10000.00, 100.00, 28300.00, 'Samuel Carter',    '250791666666', NULL, NULL, NULL,    NULL, NULL,                                   3, 4, '*165*S*10000 RWF transferred to Samuel Carter (250791666666) from 36521838 at 2024-05-11 20:34:47. Fee was: 100 RWF. New balance: 28300 RWF.'),
(13913173274,  1715506895734, '2024-05-12 11:41:28', 'AIRTIME',          'DEBIT',  2000.00,   0.00, 25280.00, 'Airtime',           NULL,           NULL, NULL, NULL,    '',   NULL,                                   5, 5, '*162*TxId:13913173274*S*Your payment of 2000 RWF to Airtime with token  has been completed at 2024-05-12 11:41:28. Fee was 0 RWF. Your new balance: 25280 RWF.'),
(14262449979,  1717683548224, '2024-06-06 16:19:01', 'MERCHANT_DEBIT',   'DEBIT',  600.00,    0.00,   230.00, 'ITEC Ltd',          NULL,           NULL, NULL, NULL,    NULL, 'c5e8bfeb-33d8-4eb2-8d22-154e5ff5e310', 6, 1, '*164*S*A transaction of 600 RWF by INFORMATION TECHNOLOGY ENGINEERING CONSTRUCTION ITEC Ltd was successfully completed at 2024-06-06 16:19:01. Your new balance:230 RWF.'),
(14324965479,  1718079981570, '2024-06-11 06:26:11', 'BUNDLE',           'DEBIT',  2000.00,   0.00,   350.00, 'Bundles and Packs', NULL,           NULL, NULL, NULL,    '',   NULL,                                   7, 2, '*162*TxId:14324965479*S*Your payment of 2000 RWF to Bundles and Packs with token  has been completed at 2024-06-11 06:26:11. Fee was 0 RWF. Your new balance: 350 RWF.');


-- Junction table — Lancelot's participation data
INSERT INTO transaction_participants (transaction_id, user_id, role)
SELECT t.transaction_id, 2, 'SENDER'
FROM transactions t WHERE t.momo_tx_id = 76662021700
UNION ALL
SELECT t.transaction_id, 1, 'RECEIVER'
FROM transactions t WHERE t.momo_tx_id = 76662021700
UNION ALL
SELECT t.transaction_id, 1, 'SENDER'
FROM transactions t WHERE t.momo_tx_id = 73214484437
UNION ALL
SELECT t.transaction_id, 2, 'RECEIVER'
FROM transactions t WHERE t.momo_tx_id = 73214484437
UNION ALL
SELECT t.transaction_id, 1, 'ACCOUNT_OWNER'
FROM transactions t WHERE t.sms_unix_timestamp = 1715445936412
UNION ALL
SELECT t.transaction_id, 1, 'SENDER'
FROM transactions t WHERE t.sms_unix_timestamp = 1715452495316
UNION ALL
SELECT t.transaction_id, 3, 'RECEIVER'
FROM transactions t WHERE t.sms_unix_timestamp = 1715452495316
UNION ALL
SELECT t.transaction_id, 4, 'AGENT'
FROM transactions t WHERE t.momo_tx_id = 14262449979
UNION ALL
SELECT t.transaction_id, 1, 'RECEIVER'
FROM transactions t WHERE t.momo_tx_id = 14262449979
UNION ALL
SELECT t.transaction_id, 1, 'SENDER'
FROM transactions t WHERE t.momo_tx_id = 13913173274;