-- =============================================================
-- Team Croissant · MoMo SMS Data Pipeline
-- File: database/users.sql
-- Owner: Imanzi Beni
-- Description: Creates the Users table and inserts sample data
-- =============================================================

CREATE TABLE users (
    user_id    INT          NOT NULL AUTO_INCREMENT  COMMENT 'Surrogate primary key, autogenerated integer, uniquely identifies each user',
    full_name  VARCHAR(120) NOT NULL                 COMMENT 'Full name of the person or organisation as printed in the SMS message',
    phone      VARCHAR(20)  NULL                     COMMENT 'Phone number stored as text because values can be masked e.g. *********013 or carry a country prefix e.g. 250791666666',
    user_type  ENUM(
                   'CUSTOMER',
                   'AGENT',
                   'MERCHANT',
                   'OWNER'
               )            NOT NULL DEFAULT 'CUSTOMER' COMMENT 'Classifies the user role: CUSTOMER for ordinary users, AGENT for MoMo agents, MERCHANT for businesses, OWNER for the account holder',
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp when this user record was first inserted by the pipeline',

    PRIMARY KEY (user_id)

) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COMMENT='Stores every distinct person or organisation involved in a MoMo transaction';


INSERT INTO users (full_name, phone, user_type) VALUES
    ('Jane Smith',    '250781234013', 'CUSTOMER'),
    ('Samuel Carter', '250791666666', 'CUSTOMER'),
    ('Linda Green',   '250788123456', 'MERCHANT'),
    ('Alex Doe',      '250722345678', 'AGENT'),
    ('Robert Brown',  '250733456789', 'CUSTOMER');